repos:
- repo: git://github.com/pecigonzalo/pre-commit-shfmt
  rev: master
  hooks:
  - id: shell-fmt

- repo: git://github.com/coyainsurance/pre-commit-scalafmt
  rev: master
  hooks:
  - id: scalafmt
    args: [-s, -v2.4.1, -o, 'org.scalameta']

- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-case-conflict
    - id: check-merge-conflict

- repo: git://github.com/Yelp/detect-secrets
  rev: v1.1.0
  hooks:
  - id: detect-secrets
    args: ['--baseline', '.secrets.baseline']
    exclude: .*/tests/.*
